// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum LogLevel
{
	Trace("45a2ef07-f811-450c-bc23-d7e0f98a4750"),
	Debug("3e533790-a107-4a7c-9cf5-45fe73cdfe9e"),
	Info("a9b07977-b38d-4c33-aceb-7cde05924544"),
	Warning("901a5507-7401-425a-8eda-5c5d682fc0e8"),
	Error("243be978-3613-422f-a0d6-cd267c9ba626"),
	Critical("1a79d55b-a4e7-4b3b-b1fb-99a2b47fdfac");

	private final java.lang.String i18nCaptionKey;
	
	private LogLevel(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
