// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum LogLevel
{
	Trace("2f4aee83-b725-4b37-804a-5de8f74160ec"),
	Debug("2e145180-9782-433c-9645-b5f2e0824130"),
	Info("8809e227-d808-452f-818c-6acc7ee5faf7"),
	Warning("e0119f26-dea6-4c9d-8db0-820394e3289f"),
	Error("058af110-5515-45b2-83f1-1e8b28965465"),
	Critical("69a2b087-a2ee-423c-aa53-7ff19ca89213");

	private final java.lang.String i18nCaptionKey;
	
	private LogLevel(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
