// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum LogLevel
{
	Trace("7bc53e57-ea2d-4f2e-9f03-b39f14da7242"),
	Debug("be9f664b-2181-4e5a-98f2-d4aef94ffcf2"),
	Info("61ab0ec3-edb0-4303-821a-26d90735aea3"),
	Warning("ff50458c-ef63-4aba-9eaf-61fdcc07a74c"),
	Error("0b202b4e-491a-40a4-861f-4e5bdc9908b6"),
	Critical("ec9767d8-e908-4629-8327-79fd006f379f");

	private final java.lang.String i18nCaptionKey;
	
	private LogLevel(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
