// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum SanitizerPolicy
{
	BLOCKS("05473525-4dae-469b-8909-259f06d24e3a"),
	FORMATTING("6fec113c-d22d-4df2-9f5d-01b6ac76fbdc"),
	IMAGES("fd0ddb2f-7c20-4072-b3e6-6a8d158ebc07"),
	LINKS("536afc27-d4ce-4027-a409-e9978c440fb6"),
	STYLES("0bcc7951-1746-4918-8b05-30f71906eae6"),
	TABLES("fc54daa6-cf27-41a5-8a28-89f05f316ca1");

	private final java.lang.String i18nCaptionKey;
	
	private SanitizerPolicy(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
