// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum SanitizerPolicy
{
	BLOCKS("2ba37505-a523-41de-a088-718573dba2a1"),
	FORMATTING("b8e314c7-1796-4e1d-9dc3-4e2564854071"),
	IMAGES("a265bdc4-35f7-405c-96aa-2d1d0b1187bc"),
	LINKS("9a593f8e-db5e-46ba-86fe-8fcb4b8a9354"),
	STYLES("f74c8134-ee21-4dd1-aaec-33b0cc2f0cc8"),
	TABLES("76586c5f-f3a8-4152-af65-14796ec944f0");

	private final java.lang.String i18nCaptionKey;
	
	private SanitizerPolicy(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
