// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum SanitizerPolicy
{
	BLOCKS("ff6d9bca-0cab-4d9d-aaf7-9ee196b14fbc"),
	FORMATTING("ab138a27-ec13-4fd5-8129-6b6dc3a832eb"),
	IMAGES("ec4bfdcc-24d0-410f-ad07-12654555f822"),
	LINKS("6c335fab-e671-4270-ada3-6d9b2448f2a9"),
	STYLES("953535c5-9ec0-4d2d-83b7-d0e762629e47"),
	TABLES("86c3bc67-0966-4502-a0ae-90e68ab39504");

	private final java.lang.String i18nCaptionKey;
	
	private SanitizerPolicy(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
