// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum StandardEncodings
{
	US_ASCII("912effaa-d304-44b5-bd69-f1bd3b715cf7"),
	ISO_8859_1("59e854c3-2951-4926-9495-3ec921c71675"),
	UTF_8("d27ecef4-8824-4487-bd8a-d95f3837c38f"),
	UTF_16BE("35ac97ed-5eed-4512-b08b-93fd3f306526"),
	UTF_16LE("fdd870e5-4c54-453a-84ab-67d90285ce0f"),
	UTF_16("edfc7328-60da-4d3f-80bb-23729b1c345a");

	private final java.lang.String i18nCaptionKey;
	
	private StandardEncodings(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
