// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum StandardEncodings
{
	US_ASCII("73e8bbba-0ae2-418d-aaeb-dc093ec56447"),
	ISO_8859_1("c66a2ce9-f24d-4f74-9fee-dff156f0302b"),
	UTF_8("2a108b7b-dd95-4f48-a4c6-860312b45ea2"),
	UTF_16BE("6cfa8e17-8c4b-48e9-8fe8-07dbd4b377d5"),
	UTF_16LE("fc11dcb6-82c1-4b06-85c9-96d9b43c5984"),
	UTF_16("c1f4f78e-5fce-4701-aa74-46895207e033");

	private final java.lang.String i18nCaptionKey;
	
	private StandardEncodings(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
