// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum StandardEncodings
{
	US_ASCII("7e9f496f-1407-4611-94a5-6388437899ce"),
	ISO_8859_1("f8952ebf-86f1-44c6-8052-05420b850ad6"),
	UTF_8("92788473-8d04-4291-b797-4a7327f81709"),
	UTF_16BE("3815748c-df55-47af-afdb-431825d3cac6"),
	UTF_16LE("af049d5b-cc2c-416b-a45b-dbf8825e71fc"),
	UTF_16("1942fc1b-afcb-4ebc-9af2-c307b7b670d6");

	private final java.lang.String i18nCaptionKey;
	
	private StandardEncodings(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
