// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package webactions.proxies;

public enum PictureQuality
{
	original("90533921-0070-48b8-8978-b5d79029c75c"),
	low("ec2faaaa-780b-4981-a112-0fa8b8cc3311"),
	medium("f5c2ee28-66dd-4046-a0d9-662cbaf56102"),
	high("3d141ebf-53ca-4580-be9d-efb4c6498c61"),
	custom("cb8c15d7-9a24-4ad0-b6f9-5510f3cefc8d");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
