// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package webactions.proxies;

public enum PictureQuality
{
	original("f7711c1a-1ed9-4771-b9fa-26ee19b19f4b"),
	low("cadf8342-9262-4a7b-8d98-01e5b9d4bc53"),
	medium("6d989879-f962-4b5c-9d9a-d63a0658700b"),
	high("0dfcede8-8f87-4481-9ebd-8ee114451f9e"),
	custom("2ac5bcbd-0b31-4a28-811e-176cf14e5f41");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
