// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package documentgeneration.proxies;

public enum Enum_DeploymentType
{
	MendixPublicCloud("e5c8c629-0ba5-492c-8c36-b676c33388db"),
	MendixPrivateCloud("8964eca6-e898-485b-899f-46f3a912d66c"),
	MendixCloudDedicated("62a21783-8549-4004-b101-96b08c405bd6"),
	Other("6dcf70ff-1c31-4f28-9efc-ce46322f6832");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_DeploymentType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
