// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package documentgeneration.proxies;

public enum Enum_ServiceType
{
	_Local("37bcfbf5-c134-4620-abbb-419408d4a0e7"),
	_Cloud("a3b9ed52-6c05-4f4e-b7b5-29c9c2b2e96f"),
	_Private("5f7b2603-adde-46c5-89d6-2c26597fabdb");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_ServiceType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
