// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package documentgeneration.proxies;

public enum Enum_DocumentRequest_Status
{
	Pending("2a6cae17-9ce1-4b5a-938b-4eac7f8ad9cb"),
	Completed("8d7facb3-375d-4101-b214-2d550bacf84e"),
	Failed("3a4f0495-dec9-4a44-a31f-8129176468fd");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_DocumentRequest_Status(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
