// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package documentgeneration.proxies;

public enum Enum_DocumentRequest_Status
{
	Pending("79adb33d-056f-4474-8a93-3c0b945d53c0"),
	Completed("a6a48f4f-2ff0-4463-b62e-f208f7e5b5d3"),
	Failed("40fc899b-7347-4f1d-8007-6cce47f62b83");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_DocumentRequest_Status(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
