// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package documentgeneration.proxies;

public enum Enum_ServiceType
{
	_Local("a16a9a89-bb64-4778-9010-5339d7af7396"),
	_Cloud("9db6f693-ad92-49de-a4f0-776b09872d0c"),
	_Private("dc6fe758-41db-459d-ba66-e75d7bdb6f30");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_ServiceType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
