// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("85529431-181b-4207-82c6-be5751f22665"),
	startsWith("3764e1d7-0782-4d86-9ec6-9881d89a190f"),
	endsWith("fe3c24bf-f5ad-4ec9-a87e-05b9fb926a49"),
	between("8b16e11d-409a-4c30-a5e1-0545ca362c07"),
	greater("d04b39dc-3015-42e4-815c-dd6e17611701"),
	greaterEqual("c9e67b7e-4358-49ca-8660-ed5df12a1075"),
	equal("c124e5f9-7fd0-4fc8-a6b0-9223a38578cf"),
	notEqual("d490a1f1-1ff8-4683-8209-61019857e2ac"),
	smaller("68255371-abfe-48dd-abb3-c33fabaf09fd"),
	smallerEqual("45c9b329-e815-4446-90d2-52f27b9680b2"),
	empty("9937be75-3676-4b85-9160-8e53953c122a"),
	notEmpty("d7bddb52-ff4d-4ca4-8b53-7c2eead6bf02");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
