// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("222b64a7-cbc0-4c40-b6a0-e8581796ca55"),
	startsWith("a2288881-1855-40b1-8026-23725c625ddd"),
	endsWith("4461c5a2-5720-4840-af1c-578fbb2f3353"),
	between("1894ff79-1dd6-4f10-a065-541e25da66fa"),
	greater("6335cd4e-9828-4c89-9c53-e7009f2c3c49"),
	greaterEqual("3ce595bd-18e0-44a2-9e18-d22ad82aff08"),
	equal("fb2d3e6f-8514-4c0d-abb0-e2d0ffab5aa0"),
	notEqual("9bb68ec4-c6e5-4979-809a-650c22e8a3a9"),
	smaller("f20c60a0-3da9-4d45-9fc6-f3a3e5896cea"),
	smallerEqual("3c0f6705-c9b6-4ec3-8485-8b3e0544d3bc"),
	empty("3929a8eb-c81a-4322-a525-1e67aa8ff1c4"),
	notEmpty("0cec3f75-9003-44c3-8de0-60b0ae9e2794");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
